identifier: le0cc1k1z627t8j7
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: angular-starter
homeFolder: C:\@Projects\@Personal\angular-starter
distFolder: ./dist/angular-starter
outDir: C:\@Projects\@Personal\angular-starter\dist\static
handle404: ''
